### ISSUE TITLE
移动端操作略不方便

### ISSUE THREAD

**Issue by Urushibara-Ruka** [CJowo/pcr-guild-vue#1]
**1. 希望前端页面能对移动端进行优化
像这种还好**
![image](https://user-images.githubusercontent.com/47585312/81075030-67b51b80-8f1c-11ea-8044-bd7f8bb6daa1.png)

但是查看box页面很难受
![image](https://user-images.githubusercontent.com/47585312/81075102-82879000-8f1c-11ea-8713-facd2413bf4b.png)

**2.其次希望能增加 前/中/后卫的区分，类似 jjc作业网这样  https://pcrdfans.com/**
这样便于添加时候进行筛选，以及管理员查看（包括box查看页面分三排进行展示）

**Comment by CJowo** [comment]
感谢建议，之后会进行修改
